# Project
version=2.0.1
group=com.mrbysco.dailydad

# Common
minecraft_version=1.21.1

# NeoForge
neo_version=21.1.93
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
neogradle.subsystems.conventions.runs.create-default-run-per-type=false

# Fabric
fabric_version=0.114.2+1.21.4
fabric_loader_version=0.16.10
cloth_config_version=15.0.140
mod_menu_version=11.0.3

# Mod options
mod_name=DailyDad
mod_author=Mrbysco
mod_id=dailydad

#Publishing
curseforge_id=559851
modrinth_id=Vs0KIwAY

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false