# Project
version=3.0.0
group=com.mrbysco.dailydad

# Common
minecraft_version=26.1.2
neoform_version=26.1.2-1
mixin_version=0.17.0+mixin.0.8.7
mixinextras_version=0.5.3

# NeoForge
neo_version=26.1.2.17-beta

# Fabric
fabric_version=0.146.1+26.1.2
fabric_loader_version=0.19.2
forge_config_api_version=26.1.3
mod_menu_version=18.0.0-alpha.8

# Mod options
mod_name=DailyDad
mod_author=Mrbysco
mod_id=dailydad

#Publishing
curseforge_id=559851
modrinth_id=Vs0KIwAY

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false